services:
  etheria_global_db:
    image: postgres:16
    container_name: etheria_global_db
    environment:
      POSTGRES_USER: etheria_user
      POSTGRES_DB: etheria_global_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etheria_user -d etheria_global_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proyecto_network

  dynamic_brands_db:
    image: mysql:8.4
    container_name: dynamic_brands_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: dynamic_brands_db
      MYSQL_USER: dynamic_user
      MYSQL_PASSWORD: dynamic_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u dynamic_user --password=dynamic_password"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proyecto_network

  etl_runner:
    build: ./etl
    container_name: etl_runner
    depends_on:
      etheria_global_db:
        condition: service_healthy
      dynamic_brands_db:
        condition: service_healthy
    networks:
      - proyecto_network

  dashboard:
    build: ./dashboard
    container_name: etheria_dashboard
    ports:
      - "5000:5000"
    depends_on:
      etheria_global_db:
        condition: service_healthy
    networks:
      - proyecto_network

networks:
  proyecto_network:
    driver: bridge
